### PR TITLE
Allow a dataset to be created without a file

### PR DESCRIPTION
**Pull request by matthewma7**

### CODE REVIEW

**Comment by dorukozturk** [comment]
@matthewma7 I fixed the gdal issue with CI. Can you take a look at the failing test to see if it is related to your changes?

**Comment by matthewma7** [comment]
@dorukozturk Thank you very much for fixing the build. I reverted my change for testing, it looks like the new error is related to something else.

**Comment by dorukozturk** [comment]
Ok, thanks for verifying. I will try to fix it later today.

**Comment by matthewma7** [comment]
@dorukozturk It looks all right to me. Thank you for fixing the CI. 
We can merge it now.

**Pull request merged**
